FROM php:8.1-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    zip \
    && rm -rf /var/lib/apt/lists/*

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR /app

# Copy app files into image
COPY . .

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql

# Install PHP dependencies
RUN composer install

EXPOSE 8000

# Start PHP built-in server after dumping autoload
ENTRYPOINT ["sh", "-c", "composer dump-autoload && php -S 0.0.0.0:8000 -t public"]
